In [1]:
from __future__ import division
import numpy as np
import warnings

In [2]:
y_true = np.array([[1,0,1,1],[0,1,0,0],[0,0,0,0],[0,1,1,0]])
y_pred = np.array([[0,0,1,1],[1,1,0,1],[0,1,0,0],[1,1,1,1]])

In [3]:
#y_true = np.array([[1,0,1,1,1],[0,1,0,0,0],[0,0,0,0,1],[0,1,1,0,1]])
#y_pred = np.array([[0,0,1,1,1],[1,1,0,1,0],[0,1,0,0,0],[1,1,1,1,1]])

In [4]:
def pre_cal(target, prediction, print_all = False):
    if(target.shape != prediction.shape):
        print("Wrong predictions matrix!")

    real_pos = real_neg = pred_pos = pred_neg  = true_pos = true_neg = []

    for i in range(y_true.shape[0]):
        # real values
        real_pos = np.asarray(np.append(real_pos,np.logical_and(y_true[i], y_true[i]).sum()), dtype=np.int64).reshape(-1,1) 
        real_neg = np.asarray(np.append(real_neg,np.logical_and(np.logical_not(y_true[i]),np.logical_not(y_true[i])).sum()), dtype=np.int64).reshape(-1,1)

        # predicted values
        pred_pos = np.asarray(np.append(pred_pos,np.logical_and(y_pred[i], y_pred[i]).sum()),dtype=np.int64).reshape(-1,1)
        pred_neg = np.asarray(np.append(pred_neg,np.logical_and(np.logical_not(y_pred[i]), np.logical_not(y_pred[i])).sum()),dtype=np.int64).reshape(-1,1)

        # true labels
        true_pos = np.asarray(np.append(true_pos,np.logical_and(y_true[i], y_pred[i]).sum()),dtype=np.int64).reshape(-1,1)
        true_neg = np.asarray(np.append(true_neg,np.logical_and(np.logical_not(y_true[i]), np.logical_not(y_pred[i])).sum()),dtype=np.int64).reshape(-1,1)
        
    if print_all:
        result = np.concatenate((real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg), axis=1)
        print(result)
    
    return(real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg)

In [5]:
real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred, print_all = True)

[[3 1 2 2 2 1]
 [1 3 3 1 1 1]
 [0 4 1 3 0 3]
 [2 2 4 0 2 0]]


In [6]:
def divideZero( value_a, value_b):
    with np.errstate(divide='ignore', invalid='ignore'):
        result = np.true_divide( value_a, value_b )
        result[ ~ np.isfinite( result )] = 0
    return result

In [7]:
def accuracy(target, predicted):
    #return the accuracy
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)   
    score = (true_pos + true_neg)/(pred_pos + pred_neg)
    score = np.mean(score)
    return score

In [8]:
accuracy(y_true, y_pred)

0.625

In [9]:
def precision(target, predicted):
    #return precision
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)     
    score = divideZero(true_pos, pred_pos)
    score = np.mean(score)
    return score

In [10]:
precision(y_true, y_pred)

0.45833333333333331

In [11]:
def recall(target, predicted):
    #return recall
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)    
    score = divideZero(true_pos, real_pos)
    score = np.mean(score)
    return score

In [12]:
recall(y_true, y_pred)

0.66666666666666663

In [13]:
def fscore(target, predicted,beta = 1):
    prec, rec = precision(y_true, y_pred), recall(y_true, y_pred)
    beta_val = beta*beta
    score = ((1+beta_val)*(prec*rec))/(beta_val*(prec+rec))
    return score

In [14]:
fscore(y_true, y_pred)

0.54320987654320985

In [15]:
def microprecision(target, predicted):
    #return micro-precision
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)
    score = true_pos.sum()/pred_pos.sum()
    return score

In [16]:
microprecision(y_true, y_pred)

0.5

In [17]:
def microrecall(target, prediction):
    #return micro-recall
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)
    score = true_pos.sum()/real_pos.sum()
    return score

In [18]:
microrecall(y_true, y_pred)

0.83333333333333337

In [19]:
def microfscore(target, predicted,beta = 1):
    #return micro-fscore
    prec, rec = microprecision(y_true, y_pred), microrecall(y_true, y_pred)
    beta_val = beta*beta
    score = ((1+beta_val)*(prec*rec))/(beta_val*(prec+rec))
    return score

In [20]:
microfscore(y_true, y_pred)

0.625

In [21]:
def macroprecision(target, predicted):
    #return macro-precision
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)     
    score = divideZero(true_pos, pred_pos)
    return score

In [22]:
macroprecision(y_true, y_pred)

array([[ 1.        ],
       [ 0.33333333],
       [ 0.        ],
       [ 0.5       ]])

In [23]:
def macrorecall(target, predicted):
    #return macro-recall
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)    
    score = divideZero(true_pos, real_pos)
    return score

In [24]:
macrorecall(y_true, y_pred)

array([[ 0.66666667],
       [ 1.        ],
       [ 0.        ],
       [ 1.        ]])

In [25]:
def macrofscore(target, predicted,beta = 1):
    prec, rec = macroprecision(y_true, y_pred), macrorecall(y_true, y_pred)
    beta_val = beta*beta
    score = divideZero(((1+beta_val)*(prec*rec)),(beta_val*(prec+rec)))
    score = np.mean(score)
    return score

In [26]:
macrofscore(y_true,y_pred)

0.4916666666666667

In [27]:
def hamloss(target, predicted):
    hamloss = list()
    for i in range(y_true.shape[0]):
        hamloss = np.asarray(np.append(hamloss,np.logical_xor(y_true[i], y_pred[i]).sum()), dtype=np.int64).reshape(-1,1) 
    score = (hamloss.sum())/((y_true.shape[0])*(y_true.shape[1]))
    return score

In [28]:
hamloss(y_true,y_pred)

0.375

In [29]:
def subset(target, predicted):
    subset_matrix = list()
    for i in range(y_true.shape[0]):
        subset_matrix = np.asarray(np.append(subset_matrix, np.array_equal(y_true[i],y_pred[i])), dtype=np.int64).reshape(-1,1)
    score = (subset_matrix.sum())/((y_true.shape[0])*(y_true.shape[1]))
    return score

In [30]:
subset(y_true,y_pred)

0.0

In [31]:
def zeroloss(target, predicted):
    condition = list()
    index = list()
    for i in range(y_true.shape[0]):
        new_true = new_pred = list()
        condition = np.logical_and(y_true[i],y_true[i]).sum()
        if (condition==0):
            index = np.asarray(np.append(index,i), dtype = np.int64)

        new_true = np.delete(y_true,index, axis = 0)
        new_pred = np.delete(y_pred,index, axis = 0)
    return new_true, new_pred

In [32]:
#y_true, y_pred = zeroloss(y_true,y_pred)

In [33]:
from sklearn.metrics import zero_one_loss
zero_one_loss(y_true,y_pred)

1.0